pipeline{
    agent any
    stages{
        stage('Launch'){
            steps{
              sh "docker run -p 8080:8080 matheusdocker95/gocalculator/calculator:calculator"
            }
        }
    }
}